version: 2
updates:
  # Enable version updates for Bundler (Ruby gems)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "22:15"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "hbgsamfall"
      - "hbgsamfall2"
    # Group minor and patch updates together to reduce PR noise
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"

