# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hässelby Gårds Samfällighetsförening
email: hbgsamfall@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sida där styrelsen informerar om nyheter och ger annan information om Hässelby Gårds Samfällighetsförening
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings

# Remote theme - updated to latest version (v0.10.1, January 2025)
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

logo: "/wp-content/uploads/2022/09/hgs_logo_small.png"
search_enabled: false
last_edit_timestamp: true


#collections:
#  about:
#    output: true
#  styrelsen_info:
#    output: true
#  maintenance:
#    output: true
#  yearly:
#    output: true
#  relining:
#    output: true
#     
#just_the_docs:
#  collections:
#    about:
#      name: Om HGS
#      nav_fold: true
#    styrelsen_info:
#      name: Styrelsen informerar
#      nav_fold: true
#    maintenance:
#     name: Underhållsplan
#    yearly:
#     name: Årsmöte
#    relining:
#     name: Rörförnyelse
